"""
GenVM deploys a single file's raw bytes as the contract code -- it has no
access to sibling files in this repo, so `from contracts.cleaner import
clean` (which works fine locally and in pytest) fails inside the runtime
with `ModuleNotFoundError: No module named 'contracts'`.

This script inlines contracts/cleaner.py, trap.py, and judge.py into a
single self-contained file, contracts/evidence_guard_bundle.py, which is
what actually gets deployed. The source-of-truth, unit-tested modules stay
exactly as they are for local development and pytest; this only reassembles
their already-tested bodies, it doesn't rewrite any logic.

Run: python deploy/build_bundle.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
OUT_PATH = CONTRACTS / "evidence_guard_bundle.py"

DEPENDS_HEADER = (
    '# { "Depends": "py-genlayer:'
    '1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }'
)

# Import/local-cross-import lines to drop from each source file: they're
# either merged into the shared header once, or become unnecessary once
# everything lives in one module namespace.
#
# Matched structurally rather than by exact string. An earlier version kept
# a literal set of import lines here, which silently stopped matching the
# moment an import was edited: the cross-module imports then survived into
# the bundle and it failed on chain with ModuleNotFoundError. Anything that
# imports from `contracts.` is local and must never reach the bundle.
_LOCAL_IMPORT_PREFIX = "from contracts."
_HOISTED_IMPORT_LINES = {
    "import re",
    "import json",
    "import hashlib",
    "import unicodedata",
    "from dataclasses import dataclass, field",
    "from dataclasses import dataclass",
    "from typing import Any",
    "from genlayer import *",
}


def strip_leading_docstring(source: str) -> str:
    lines = source.split("\n")
    i = 0
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    if i < len(lines) and lines[i].lstrip().startswith('"""'):
        quote = '"""'
        first_line = lines[i]
        i += 1
        if first_line.count(quote) < 2:
            while i < len(lines) and quote not in lines[i]:
                i += 1
            i += 1
    return "\n".join(lines[i:])


def strip_known_import_lines(source: str) -> str:
    """
    Remove imports that must not survive into the bundle: the stdlib ones
    hoisted into the shared header, and every local `from contracts.`
    import, including the parenthesized multi-line form.
    """
    kept = []
    skipping_multiline_local = False

    for line in source.split("\n"):
        stripped = line.strip()

        if skipping_multiline_local:
            if stripped.endswith(")"):
                skipping_multiline_local = False
            continue

        if stripped.startswith(_LOCAL_IMPORT_PREFIX):
            # Parenthesized form spans until the closing paren.
            if "(" in stripped and not stripped.endswith(")"):
                skipping_multiline_local = True
            continue

        if stripped in _HOISTED_IMPORT_LINES:
            continue

        kept.append(line)

    return "\n".join(kept)


def body_of(filename: str) -> str:
    source = (CONTRACTS / filename).read_text(encoding="utf-8")
    source = strip_leading_docstring(source)
    source = strip_known_import_lines(source)
    return source.strip("\n")


def main() -> None:
    evidence_guard_source = (CONTRACTS / "evidence_guard.py").read_text(
        encoding="utf-8"
    )
    # evidence_guard.py's own Depends header is the file's first line;
    # drop it here since the bundle supplies its own copy up top.
    evidence_guard_lines = evidence_guard_source.split("\n")
    assert evidence_guard_lines[0].strip().startswith('# { "Depends"')
    evidence_guard_source = "\n".join(evidence_guard_lines[1:])
    evidence_guard_body = strip_known_import_lines(
        strip_leading_docstring(evidence_guard_source)
    )

    sections = [
        DEPENDS_HEADER,
        (
            '"""\n'
            "Evidence Guard -- bundled, deployable single file.\n\n"
            "Generated by deploy/build_bundle.py from contracts/cleaner.py, "
            "trap.py,\njudge.py, and evidence_guard.py. Do not hand-edit -- "
            "edit the source\nmodules and regenerate. See those files for "
            "documentation of each\nstage; this file exists purely because "
            "GenVM deploys a single file\nwith no access to sibling local "
            "modules.\n\"\"\""
        ),
        "import hashlib",
        "import json",
        "import re",
        "import unicodedata",
        "from dataclasses import dataclass, field",
        "from typing import Any",
        "",
        "from genlayer import *",
        "",
        body_of("cleaner.py"),
        body_of("trap.py"),
        body_of("judge.py"),
        evidence_guard_body.strip("\n"),
    ]

    bundle = "\n\n\n".join(s.strip("\n") for s in sections) + "\n"
    OUT_PATH.write_text(bundle, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH} ({len(bundle)} bytes)")


if __name__ == "__main__":
    main()
